name: cleanarchitecture
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #state management
  flutter_bloc: ^8.1.4

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.7

  #dateFormat
  intl: ^0.19.0

  #DataBase
  floor: ^1.4.2

  #make request to the api
  retrofit: ^4.1.0

  #hooks
  flutter_hooks: ^0.20.5

  #cached image
  cached_network_image: ^3.3.1
  ionicons: ^0.2.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.1.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.8
  analyzer: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: lib/assets/fonts/Muli/Muli.ttf
        - asset: lib/assets/fonts/Muli/Muli-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Muli/Muli-Light.ttf
          weight: 300

